# Generated by Django 4.2.11 on 2024-05-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_userfarmrole_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Farm Owner'), ('manager', 'Manager'), ('shareholder', 'Shareholder'), ('guest', 'Guest')], default='Farm Owner', max_length=20),
        ),
    ]
