# Generated by Django 4.2.11 on 2024-05-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_pestcontrol_harvest_crophealth_cropcycle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='cropcycle',
            options={'verbose_name_plural': 'Crop Cycles'},
        ),
        migrations.AlterModelOptions(
            name='crophealth',
            options={'verbose_name_plural': 'Crop Health Records'},
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={'verbose_name_plural': 'Harvests'},
        ),
        migrations.AlterModelOptions(
            name='pestcontrol',
            options={'verbose_name_plural': 'Pest Controls'},
        ),
        migrations.AddField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('animal_feed', 'Animal Feed'), ('human_consumption', 'Human Consumption')], default='human_consumption', max_length=20),
        ),
        migrations.AddField(
            model_name='harvest',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('bushels', 'Bushels'), ('pounds', 'Pounds'), ('liters', 'Liters'), ('other', 'Other')], default='kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='crop',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('bushels', 'Bushels'), ('pounds', 'Pounds'), ('liters', 'Liters'), ('other', 'Other')], default='kg', max_length=50),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['name'], name='crop_crop_name_4dff7d_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['planting_date'], name='crop_crop_plantin_eeb614_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['harvest_date'], name='crop_crop_harvest_67f6be_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['category'], name='crop_crop_categor_be2ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['date'], name='crop_harves_date_cc6031_idx'),
        ),
        migrations.AddIndex(
            model_name='harvest',
            index=models.Index(fields=['quantity'], name='crop_harves_quantit_640d87_idx'),
        ),
    ]
