# Generated by Django 4.2.11 on 2024-05-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('crop', '0003_alter_crop_options_alter_cropcycle_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crop',
            name='crop_crop_categor_be2ac1_idx',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='category',
            new_name='use',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='feeds_livestock',
        ),
        migrations.AddField(
            model_name='crop',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_productions', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['use'], name='crop_crop_use_09e2fd_idx'),
        ),
    ]
