# Generated by Django 4.2.11 on 2024-04-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='reason',
        ),
    ]
