# Generated by Django 4.2.11 on 2024-05-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_leave_comments_remove_leave_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['date'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendances'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department', 'position', 'hire_date'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['date'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
        migrations.AlterModelOptions(
            name='onboarding',
            options={'verbose_name': 'Onboarding', 'verbose_name_plural': 'Onboardings'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='recruitment',
            options={'ordering': ['opening_date', 'closing_date'], 'verbose_name': 'Recruitment', 'verbose_name_plural': 'Recruitments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'priority'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hr.position'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='hr.position'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hr.employee'),
        ),
    ]
