# Generated by Django 4.2.11 on 2024-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=80)),
                ('last_name', models.CharField(default='', max_length=80)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='', max_length=80)),
                ('date_joined', models.DateField()),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
