# Generated by Django 4.2.11 on 2024-04-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0002_remove_livestock_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_date', models.DateField(verbose_name='Milking Date')),
                ('morning_volume', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Morning Volume (liters)')),
                ('evening_volume', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Evening Volume (liters)')),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock', verbose_name='Cow')),
            ],
            options={
                'verbose_name': 'Milk Production',
            },
        ),
    ]
