# Generated by Django 4.2.11 on 2024-04-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyFeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feed_type', models.CharField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
