# Generated by Django 4.2.11 on 2024-04-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_alter_dairyfeeds_options_alter_dairyfeeds_feed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milkproduction',
            name='evening_volume',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Evening Volume (liters)'),
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='morning_volume',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Morning Volume (liters)'),
        ),
    ]
