# Generated by Django 4.2.11 on 2024-04-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_remove_breeding_expected_due_date'),
        ('dairy', '0004_alter_milkproduction_evening_volume_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DairyFeeds',
            new_name='Feeds',
        ),
        migrations.RenameModel(
            old_name='MilkProduction',
            new_name='Production',
        ),
    ]
