# Generated by Django 4.2.11 on 2024-04-23 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_alter_animal_options_health_symptoms_and_more'),
        ('dairy', '0006_alter_production_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='cow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='livestock.animal', verbose_name='Cow'),
        ),
        migrations.AlterField(
            model_name='production',
            name='evening_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Evening Volume (liters)'),
        ),
        migrations.AlterField(
            model_name='production',
            name='morning_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Morning Volume (liters)'),
        ),
        migrations.AddIndex(
            model_name='feeds',
            index=models.Index(fields=['date'], name='dairy_feeds_date_266850_idx'),
        ),
        migrations.AddIndex(
            model_name='feeds',
            index=models.Index(fields=['feed_type'], name='dairy_feeds_feed_ty_266ab0_idx'),
        ),
    ]
