# Generated by Django 4.2.11 on 2024-05-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0007_alter_production_cow_alter_production_evening_volume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name': 'Milk Production', 'verbose_name_plural': 'Milk Productions'},
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['milking_date'], name='dairy_produ_milking_b00c43_idx'),
        ),
    ]
