# Generated by Django 4.2.11 on 2024-05-16 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('dairy', '0008_alter_production_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milk_productions', to='inventory.product'),
        ),
    ]
