# Generated by Django 4.2.11 on 2024-06-23 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('use', models.CharField(choices=[('animal_feed', 'Animal Feed'), ('human_consumption', 'Human Consumption')], default='human_consumption', max_length=20)),
                ('planting_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('bushels', 'Bushels'), ('pounds', 'Pounds'), ('liters', 'Liters'), ('other', 'Other')], default='kg', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_productions', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Crops',
            },
        ),
        migrations.CreateModel(
            name='PestControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pest_type', models.CharField(max_length=100)),
                ('control_method', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.crop')),
            ],
            options={
                'verbose_name_plural': 'Pest Controls',
            },
        ),
        migrations.CreateModel(
            name='CropHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('condition', models.CharField(max_length=100)),
                ('treatment', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop Health Records',
            },
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop Cycles',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('tonnes', 'Tonnes'), ('bushels', 'Bushels'), ('pounds', 'Pounds'), ('liters', 'Liters'), ('other', 'Other')], default='kg', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.crop')),
            ],
            options={
                'verbose_name_plural': 'Harvests',
                'indexes': [models.Index(fields=['date'], name='agriculture_date_6b174c_idx'), models.Index(fields=['quantity'], name='agriculture_quantit_c1762f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['name'], name='agriculture_name_295c73_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['planting_date'], name='agriculture_plantin_03aecc_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['harvest_date'], name='agriculture_harvest_f19f66_idx'),
        ),
        migrations.AddIndex(
            model_name='crop',
            index=models.Index(fields=['use'], name='agriculture_use_252703_idx'),
        ),
    ]
