# Generated by Django 4.2.11 on 2024-05-16 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Inventory Category', 'verbose_name_plural': 'Inventory Categories'},
        ),
    ]
