# Generated by Django 4.2.11 on 2024-04-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='livestock',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('condition', models.CharField(max_length=100)),
                ('treatment', models.TextField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock')),
            ],
        ),
    ]
