# Generated by Django 4.2.11 on 2024-04-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_remove_livestock_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField()),
                ('expected_due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('condition', models.CharField(max_length=100)),
                ('treatment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cause_of_death', models.CharField(max_length=100)),
                ('disposal_method', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrus_detection_date', models.DateField()),
                ('pregnancy_status', models.BooleanField(default=False)),
                ('calving_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_administered', models.DateField()),
                ('dosage', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='livestock',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HealthRecord',
        ),
        migrations.AddField(
            model_name='vaccination',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock'),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock'),
        ),
        migrations.AddField(
            model_name='mortality',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock'),
        ),
        migrations.AddField(
            model_name='health',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.livestock'),
        ),
        migrations.AddField(
            model_name='breeding',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeding_s', to='livestock.livestock'),
        ),
        migrations.AddField(
            model_name='breeding',
            name='mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mates', to='livestock.livestock'),
        ),
    ]
