# Generated by Django 4.2.11 on 2024-04-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_breeding_health_mortality_reproduction_vaccination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livestock',
            old_name='identification_number',
            new_name='id_number',
        ),
    ]
