# Generated by Django 4.2.11 on 2024-04-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0002_dairyfeeds'),
        ('livestock', '0004_rename_identification_number_livestock_id_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livestock',
            new_name='Animal',
        ),
    ]
