# Generated by Django 4.2.11 on 2024-04-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_rename_livestock_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breeding',
            name='expected_due_date',
        ),
    ]
