# Generated by Django 4.2.11 on 2024-04-23 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_remove_breeding_expected_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['id_number'], 'verbose_name_plural': 'animals'},
        ),
        migrations.AddField(
            model_name='health',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='reaction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breedings', to='livestock.animal'),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='mate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mated_with', to='livestock.animal'),
        ),
    ]
