# Generated by Django 4.2.11 on 2024-05-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_alter_animal_options_health_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breeding',
            options={'verbose_name_plural': 'breeding records'},
        ),
        migrations.AlterModelOptions(
            name='health',
            options={'verbose_name_plural': 'health records'},
        ),
        migrations.AlterModelOptions(
            name='mortality',
            options={'verbose_name_plural': 'mortalities'},
        ),
        migrations.AlterModelOptions(
            name='reproduction',
            options={'verbose_name_plural': 'reproduction records'},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name_plural': 'vaccinations'},
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='reaction',
        ),
        migrations.AlterField(
            model_name='animal',
            name='health_status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('recovering', 'Recovering'), ('unknown', 'Unknown')], default='healthy', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='id_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
